const mockData = {
  user1: {
    firstName: 'Niyonsenga',
    lastName: 'Eric',
    gender: 'male ',
    passportNumber: '12345x7ii',
    email: 'mxx@gmail.com',
    password: 'Niyonkuru1',
  },
  existingPassport: {
    firstName: 'Niyonsenga',
    lastName: 'Eric',
    gender: 'male ',
    passportNumber: '12345x7ii',
    email: 'maa@gmail.com',
    password: 'Niyonkuru1',
  },
  incorectFirstName: {
    firstName: 'Niyonsenga@',
    lastName: 'Eric',
    gender: 'male ',
    passportNumber: '1bx45x7ii',
    email: 'mub@gmail.com',
    password: 'Niyonkuru1',
  },
  incorectlastName: {
    firstName: 'Niyonsenga',
    lastName: 'Eric@',
    gender: 'male ',
    passportNumber: '1bx45x7ii',
    email: 'mub@gmail.com',
    password: 'Niyonkuru1',
  },
  incorectEmail: {
    firstName: 'Niyonsenga',
    lastName: 'Eric',
    gender: 'male ',
    passportNumber: '1bx45x8ii',
    email: 'mubgmail.com',
    password: 'Niyonkuru1',
  },
  invalidPassport: {
    firstName: 'Niyonsenga',
    lastName: 'Eric',
    gender: 'male ',
    passportNumber: '1bx',
    email: 'nn@gmail.com',
    password: 'Niyonkuru@1',
  },
};
export default mockData;
