const mockData = {
  userWithLineManager: {
    firstName: 'mugisha',
    lastName: 'desire',
    gender: 'male',
    passportNumber: 'dear38bh',
    email: 'mugishadesire@gmail.com',
    password: 'Niyonkuru@1',
    lineManager: 'william.ishimwe@andela.com',
  },
  loginUserWithLineManager: {
    email: 'mugishadesire@gmail.com',
    password: 'Niyonkuru@1',
  },
  loginUserWithLineManager2: {
    id: 7,
    firstName: 'murenzi',
    lastName: 'james',
    gender: 'male',
    passport: 'dear78bh',
    email: 'murenzijames@gmail.com',
    role: 'requester',
    method: 'standard',
    clientId: null,
    lineManager: 'william.ishimwe@andela.com',
  },
  userX: {
    firstName: 'nameless',
    lastName: 'nobobody',
    gender: 'male',
    passportNumber: '12348234',
    email: 'nameless@gmail.com',
    password: 'Password@1',
  },
  loginNewUser: {
    id: 5,
    firstName: 'david',
    lastName: 'Himbara',
    gender: 'male',
    email: 'multi-city@gmail.com',
    passport: 'ml846531',
    role: 'requester',
    method: 'standard',
    lineManager: 'eugene.munyampundu@gmail.com',
  },
  loginX: {
    id: 12,
    firstName: 'Barefoot',
    lastName: 'Nomade',
    gender: 'male',
    passportNumber: '78byvttt',
    email: 'brftnomad@gmail.com',
  },
  reguralUser: {
    id: 11,
    firstName: 'William',
    lastName: 'Ishimwe',
    role: 'requester',
    gender: 'male',
    email: 'ishimwewil005@gmail.com',
    lineManager: 'william.ishimwe@andela.com',
    method: 'standard',
    clientId: '1234566',
  },
  user1: {
    firstName: 'Niyonsenga',
    lastName: 'Eric',
    gender: 'male',
    passportNumber: '78byvttt',
    email: 'brftnomad@gmail.com',
    password: 'Niyonkuru@1',
  },
  login1: {
    email: 'brftnomad@gmail.com',
    password: 'Niyonkuru@1',
  },
  user5: {
    firstName: 'Niyonsenga',
    lastName: 'Eric',
    gender: 'male',
    passportNumber: '67uh09re',
    email: 'niyeric11@gmail.com',
    password: 'Niyonkuru@1',
  },
  user10: {
    firstName: 'Moise',
    lastName: 'Rwibutso',
    gender: 'male',
    passportNumber: '78bh675p',
    email: 'moiserwi@gmail.com',
    password: 'Niyonkuru@1',
  },
  existingPassport: {
    firstName: 'Niyonsenga',
    lastName: 'Eric',
    gender: 'male ',
    passportNumber: '12345678',
    email: 'brftnomad@gmail.com',
    password: 'Niyonkuru@1',
  },
  validOneWayTrip: {
    origin: 'Kigali',
    destination: "'Kampala",
    departureDate: '2080-01-11',
    returnDate: '2081-01-15',
    reason: 'meet Egyptians',
    accommodation: 'Egyptian Hotel',
  },
  incorectFirstName: {
    firstName: 'Niyonsenga@',
    lastName: 'Eric',
    gender: 'male ',
    passportNumber: '1234incofn',
    email: 'brftnomad@gmail.com',
    password: 'Niyonkuru@1',
  },
  incorectlastName: {
    firstName: 'Niyonsenga',
    lastName: 'Eric@',
    gender: 'male ',
    passportNumber: '1bx45x7ii',
    email: 'brftnomad@gmail.com',
    password: 'Niyonkuru@1',
  },
  incorectEmail: {
    firstName: 'Niyonsenga',
    lastName: 'Eric',
    gender: 'male ',
    passportNumber: '1bx45x8ii',
    email: 'mubgmail.com',
    password: 'Niyonkuru1',
  },
  loginM: {
    email: 'multi-city@gmail.com',
    password: 'Niyonkuru@1',
  },
  comment: {
    comment: 'Holy',
  },
  InvalidComment: {
    comment: 'p',
  },
  invalidPassport: {
    firstName: 'Niyonsenga',
    lastName: 'Eric',
    gender: 'male ',
    passportNumber: '1bx',
    email: 'brftnomad@gmail.com',
    password: 'Niyonkuru@1',
  },
  tooManyPassportNumber: {
    firstName: 'Niyonsenga',
    lastName: 'Eric',
    gender: 'male ',
    passportNumber: '@!11111111111111111111111',
    email: 'manyNumber@gmail.com',
    password: 'Niyonkuru@1',
  },
  newPassword: {
    newPassword: 'Niyonkuru@1',
    confirmPassword: 'Niyonkuru@1',
  },
  token: {
    token:
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MSwiaWF0IjoxNTgyNjQ4ODg4LCJleHAiOjE1ODI2NTI0ODh9.7AMsqKFdwWA08O3jGjjJTLAKR_ShWc7edjuKC9jbBiY',
  },
  fakeToken: {
    token:
      'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmaXJzdE5hbWUiOiJOaXlvbnNlbmdhIiwibGFzdE5hbWUiOiJFcmljIiwiZ2VuZGVyIjoibWFsZSIsInBhc3Nwb3J0TnVtYmVyIjoiNzhieXZ0dHQiLCJlbWFpbCI6ImJyZnRub21hZEBnbWFpbC5jb20iLCJwYXNzd29yZCI6Ik5peW9ua3VydUAxIiwiaWF0IjoxNTgyNjU5NDU5fQ.I05YSeXG45B4XED9A64oUv5XkQyPrvKJnbJjWKkwe4w',
  },
  invalidNewPassword1: {
    newPassword: 'Budha@1914324235345d',
    confirmPassword: '',
  },
  email: {
    email: 'brftnomad@gmail.com',
  },
  user2: {
    email: 'kgali@gmail.com',
    password: '12345Six@',
  },
  loginSuccessfully: {
    id: 4,
    firstName: 'William',
    lastName: 'Ishimwe',
    gender: 'male',
    email: 'willishimw@gmail.com',
    passport: 'nkhydf65',
    role: 'requester',
    method: 'standard',
    clientId: null,
  },
  loginSuccessfully2: {
    id: 13,
    firstName: 'Moise',
    lastName: 'Rwibutso',
    gender: 'male',
    passportNumber: '78bh675t',
    email: 'moiserwi@gmail.com',
  },
  loginSuccessfully3: {
    id: 1,
    firstName: 'Alain',
    lastName: 'Maxim',
    gender: 'male',
    email: 'alain.maxime@gmail.com',
    passport: '12345ohc',
    role: 'requester',
    method: 'standard',
    clientId: null,
    lineManager: 'william.ishimwe@andela.com',
  },
  existingUser: {
    email: 'manzipatr@gmail.com',
    password: 'Niyonkuru@1',
  },
  invalidCredentials: {
    email: 'brftnomad@gmail.com',
    password: 'Niyonkuru',
  },
  youhaveNoAccount: {
    email: 'xx@gmail.com',
    password: 'Niyonkuru1',
  },
  missingIinformation: {
    email: 'mxx@gmail.com',
  },
  request: {
    user: 'brftnomad@gmail.com',
    type: 'one',
    reason: 'partner engagment',
    destination: 'kigali',
    status: 'pending',
    departureDate: '2020-07-01',
    returnDate: '2020-09-01',
  },
  request1: {
    user: 'rwanda2020@gmail.com',
    type: 'one',
    reason: 'partner engagment',
    destination: 'kigali',
    status: 'pending',
    departureDate: '2020-07-01',
    returnDate: '2020-09-01',
  },
  user9: {
    firstName: 'Niyonsenga',
    lastName: 'Eric',
    gender: 'male',
    passportNumber: '78byvttt',
    email: 'rwanda2020@gmail.com',
    password: 'Niyonkuru@1',
  },
  user11: {
    firstName: 'Jacques',
    lastName: 'Ikuzwe',
    gender: 'male',
    email: 'jacques@gmail.com',
    passportNumber: '784567v4',
    password: 'Password@1',
  },
  loginUser11: {
    email: 'ishimwe@gmail.com',
    password: 'Password@1',
  },
  invalidToken: {
    token: 'invalid',
  },
  managerLogin: {
    id: 2,
    firstName: 'Eugene',
    lastName: 'Munyampundu',
    gender: 'male',
    email: 'eugene.munyampundu@gmail.com',
    passport: '12349876',
    role: 'manager',
    method: 'standard',
    clientId: null,
  },
  managerLogin3: {
    id: 10,
    firstName: 'William',
    lastName: 'Ishimwe',
    gender: 'male',
    email: 'william.ishimwe@andela.com',
    passport: '123498re',
    role: 'manager',
    clientId: null,
  },
  managerLogin2: {
    id: 3,
    firstName: 'Code',
    lastName: 'Knights',
    gender: 'male',
    email: 'knights@gmail.com',
    passport: '97846531',
    role: 'manager',
    method: 'standard',
    clientId: null,
  },
  updateProfile: {
    language: 'English',
    birthDay: '12/5/067',
    currency: '£uro',
    homeTown: 'kigali',
    department: 'IT',
    lineManager: 'Reporter',
    biography:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry',
  },
  wrongPerson:
    'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MTMsImVtYWlsIjoiZXVnZW5lbXUyMjNAZ21haWwuY29tIiwiZmlyc3ROYW1lIjoiTml5b25zZW5nYSIsImxhc3ROYW1lIjoiRXJpYyIsImlhdCI6MTU4MjQwNTk0N30.xzc9O9rKH13j4kuqjLALmBeDNWtF1zlQAnpoRLD9FG4',
  multiCityRequest: {
    origin: 'New york',
    destination: 'East Africa',
    departureDate: '2020-04-28',
    returnDate: '2022-09-30',
    accommodation: 'XYZ campus',
    type: 'multi_way',
    reason: 'Reaseach',
    passportNumber: '12345677',
    cities: [
      {
        name: 'kigali',
        from: '2020-05-02',
        to: '2020-08-31',
      },
      {
        name: 'kigali',
        from: '2020-06-02',
        to: '2020-09-08',
      },
    ],
  },
  wrongMultiCityRequest: {
    destination: 'East Africa',
    departureDate: '2020-02-28',
    returnDate: '2020-03-30',
    accommodation: 'XYZ campus',
    type: 'mult',
    reason: 'Having fun',
    passportNumber: '12345677',
    cities: [
      {
        name: 'kigali',
        from: '2020-7-2',
        to: '2020-7-30',
      },
      {
        name: 'Nairobi',
        from: '2020-8-1',
        to: '2020-8-31',
      },
    ],
  },
  missingCities: {
    origin: 'New york',
    destination: 'East Africa',
    departureDate: '2020-04-28',
    returnDate: '2020-09-30',
    accommodation: 'XYZ campus',
    type: 'multi_way',
    reason: 'Reaseach',
    passportNumber: '12345677',
    cities: [
      {
        name: '',
        from: '2020-07-02',
        to: '2020-07-30',
      },
      {
        name: '',
        from: '2010-08-01',
        to: '2010-08-31',
      },
    ],
  },
  validateDate1: {
    origin: 'New york',
    destination: 'East Africa',
    departureDate: '2050-04-28',
    returnDate: '2070-09-30',
    accommodation: 'XYZ campus',
    type: 'multi_way',
    reason: 'Reaseach',
    passportNumber: '12345677',
    cities: [
      {
        name: '',
        from: '2020-07-02',
        to: '2020-07-30',
      },
      {
        name: '',
        from: '2010-08-01',
        to: '2010-08-31',
      },
    ],
  },
  validateDate2: {
    origin: 'New york',
    destination: 'East Africa',
    departureDate: '2020-04-28',
    returnDate: '2020-09-30',
    accommodation: 'XYZ campus',
    type: 'multi_way',
    reason: 'Reaseach',
    passportNumber: '12345677',
    cities: [
      {
        name: '',
        from: '2020-07-02',
        to: '2020-10-30',
      },
      {
        name: '',
        from: '2010-08-01',
        to: '2010-08-31',
      },
    ],
  },
  editRequest: {
    origin: 'Nyamata',
    destination: 'Huye',
    departureDate: '2025-02-20',
    returnDate: '2025-03-20',
    reason: 'Test update feature.',
  },
  validateDate3: {
    origin: 'New york',
    destination: 'East Africa',
    departureDate: '2020-04-28',
    returnDate: '2020-09-30',
    accommodation: 'XYZ campus',
    type: 'multi_way',
    reason: 'Reaseach',
    passportNumber: '12345677',
    cities: [
      {
        from: '2020-05-02',
        to: '2020-08-31',
      },
      {
        name: 'Nairob',
        from: '2020-06-02',
        to: '2020-09-08',
      },
    ],
  },
  booking: {
    accomodationId: 3,
    roomName: 'Room 1',
    checkinDate: '2020-06-13',
    checkoutDate: '2020-06-24',
  },
  unexistingBooking: {
    accomodationId: 30,
    roomName: 'Room 1',
    checkinDate: '2020-06-13',
    checkoutDate: '2020-06-24',
  },
  superAdminLogin: {
    id: 9,
    firstName: 'Mose',
    lastName: 'Rwibutso',
    gender: 'male',
    email: 'superadmin@barefootnomad.com',
    passport: 'ws846522',
    role: 'superAdmin',
    method: 'standard',
    clientId: null,
  },
  regularStaffLogin: {
    email: 'alain.maxime@gmail.com',
    password: 'Niyonkuru@1',
  },
  updatableUser: {
    email: 'brftnomad@gmail.com',
  },
  wrongUser: {
    email: 'xxxxxx',
  },
  newRole: {
    role: 'requester',
  },
  loginUser: {
    email: 'alain.maxime@gmail.com',
    password: 'Niyonkuru@1',
  },
  returnTripRequest: {
    origin: 'Kigali',
    destination: 'Kampala',
    departureDate: '2080-01-11',
    returnDate: '2081-01-15',
    reason: 'meet Egyptians',
    accommodation: 'Egyptian Hotel',
  },
};
export default mockData;
